// <auto-generated />
using System;
using DLL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DLL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512032426_db5")]
    partial class db5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DLL.Model.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_mon_hoc");

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("MaDiem")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ma_diem")
                        .HasComputedColumnSql("('DH'+right('0000'+CONVERT([varchar](4),[ID]),(4)))", true);

                    b.Property<decimal>("SoDiem")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("so_diem");

                    b.Property<string>("TenDiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_diem");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__diem__3213E83FAD09625C");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("diem", (string)null);
                });

            modelBuilder.Entity("DLL.Model.LopGiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_lop_hoc");

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__lop_giao__3213E83F3FDD8286");

                    b.HasIndex("IdLopHoc");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("lop_giao_vien", (string)null);
                });

            modelBuilder.Entity("DLL.Model.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoiLop")
                        .HasColumnType("int")
                        .HasColumnName("khoi_lop");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ma_lop")
                        .HasComputedColumnSql("('LH'+right('0000'+CONVERT([varchar](4),[ID]),(4)))", true);

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_lop");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__lop_hoc__3213E83FE4ECF793");

                    b.ToTable("lop_hoc", (string)null);
                });

            modelBuilder.Entity("DLL.Model.LopMon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdLop")
                        .HasColumnType("int")
                        .HasColumnName("id_lop");

                    b.Property<int?>("IdMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_mon_hoc");

                    b.Property<int?>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__lop_mon__3213E83F1B5F446A");

                    b.HasIndex("IdLop");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("lop_mon", (string)null);
                });

            modelBuilder.Entity("DLL.Model.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ma_mon")
                        .HasComputedColumnSql("('MH'+right('0000'+CONVERT([varchar](4),[ID]),(4)))", true);

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_mon");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__mon_hoc__3213E83F3D8D09B4");

                    b.ToTable("mon_hoc", (string)null);
                });

            modelBuilder.Entity("DLL.Model.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioi_tinh");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_lop_hoc");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ma_nguoi_dung")
                        .HasComputedColumnSql("('ND'+right('0000'+CONVERT([varchar](4),[ID]),(4)))", true);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nhan_xet");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenLinkAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_link_anh");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_nguoi_dung");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__nguoi_du__3213E83FA9AD549F");

                    b.HasIndex("IdLopHoc");

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("DLL.Model.Diem", b =>
                {
                    b.HasOne("DLL.Model.MonHoc", "IdMonHocNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__diem__id_mon_hoc__5070F446");

                    b.HasOne("DLL.Model.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__diem__id_nguoi_d__5165187F");

                    b.Navigation("IdMonHocNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DLL.Model.LopGiaoVien", b =>
                {
                    b.HasOne("DLL.Model.LopHoc", "IdLopHocNavigation")
                        .WithMany("LopGiaoViens")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__lop_giao___id_lo__5535A963");

                    b.HasOne("DLL.Model.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("LopGiaoViens")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__lop_giao___id_ng__5441852A");

                    b.Navigation("IdLopHocNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DLL.Model.LopMon", b =>
                {
                    b.HasOne("DLL.Model.LopHoc", "IdLopNavigation")
                        .WithMany("LopMons")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__lop_mon__id_lop__5812160E");

                    b.HasOne("DLL.Model.MonHoc", "IdMonHocNavigation")
                        .WithMany("LopMons")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__lop_mon__id_mon___59063A47");

                    b.HasOne("DLL.Model.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("LopMons")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__lop_mon__id_nguo__59FA5E80");

                    b.Navigation("IdLopNavigation");

                    b.Navigation("IdMonHocNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DLL.Model.NguoiDung", b =>
                {
                    b.HasOne("DLL.Model.LopHoc", "IdLopHocNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IdLopHoc")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__nguoi_dun__id_lo__4D94879B");

                    b.Navigation("IdLopHocNavigation");
                });

            modelBuilder.Entity("DLL.Model.LopHoc", b =>
                {
                    b.Navigation("LopGiaoViens");

                    b.Navigation("LopMons");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("DLL.Model.MonHoc", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("LopMons");
                });

            modelBuilder.Entity("DLL.Model.NguoiDung", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("LopGiaoViens");

                    b.Navigation("LopMons");
                });
#pragma warning restore 612, 618
        }
    }
}
